server:
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/takeaway?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 172.20.2.28
    #Redis服务器连接端口
    port: 6379
    password: 54#98%ag
    pool:
      #连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      #连接池中的最大空闲连接 使用负值表示没有限制
      max-idle: 8
      #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      #连接池中的最小空闲连接 此设置只有在正值时才有效果
      min-idle: 0
    #连接超时时间（毫秒）
    timeout: 30000
  application:
    name: takeaway-user
  cloud:
    nacos:
      discovery:
        server-addr: 172.20.2.28:8848
